// Button polling bits
//-----------------------------------

#ifndef BUTTON_POLLING_H_INCLUDED
#define BUTTON_POLLING_H_INCLUDED

#define BUTTON_POLL_INTERVAL_MS ( 10 / portTICK_PERIOD_MS)
#define BUTTON_FLASH_INTERVAL_MS ( 80 / portTICK_PERIOD_MS)
#define SCREEN_MSG_POP_DURATION_MS ( 1500 / portTICK_PERIOD_MS)

#define PIN_MENU_BUTTON 15
#define PIN_SET_BUTTON 4
#define PIN_UP_BUTTON 16
#define PIN_DOWN_BUTTON 17

#define PIN_SCENE_BUTTONS_BIT_1 27
#define PIN_SCENE_BUTTONS_BIT_2 14
#define PIN_SCENE_BUTTONS_BIT_4 13

#define PIN_MENU_BUTTONS_MASK  ((1ULL<<PIN_MENU_BUTTON) | (1ULL<<PIN_SET_BUTTON) | (1ULL<<PIN_UP_BUTTON) | (1ULL<<PIN_DOWN_BUTTON))

#define PIN_SCENE_BUTTONS_MASK  ((1ULL<<PIN_SCENE_BUTTONS_BIT_1) | (1ULL<<PIN_SCENE_BUTTONS_BIT_2) | (1ULL<<PIN_SCENE_BUTTONS_BIT_4) )


#define BUTTON_DEBOUNCE_TICKS 4

void button_poll_task(void);

#endif  